# Generated by Django 5.0.14 on 2026-06-06 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, verbose_name='Matrícula')),
                ('acao', models.TextField(verbose_name='Ação')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('hora', models.TimeField(auto_now_add=True, verbose_name='Hora')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-data', '-hora'],
            },
        ),
    ]
