# Generated by Django 5.0.14 on 2026-06-07 15:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Abertura')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento')),
                ('valor_abertura', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor de Abertura (Troco)')),
                ('valor_fechamento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Declarado no Fechamento')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=10, verbose_name='Status')),
                ('observacao_fechamento', models.TextField(blank=True, null=True, verbose_name='Observação de Fechamento')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caixas', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Caixa',
                'verbose_name_plural': 'Caixas',
                'ordering': ['-data_abertura'],
            },
        ),
    ]
