# Generated by Django 5.0.14 on 2026-06-08 22:38

from django.db import migrations, models


def sync_profiles_from_roles(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    admin_roles = {'Gerente Geral', 'Subgerente'}
    cashier_roles = {'Fiscal de Caixa', 'Operador de Caixa', 'Caixa'}
    stock_roles = {'Estoquista', 'Outro'}

    for user in CustomUser.objects.all().iterator():
        if user.is_superuser or user.cargo in admin_roles:
            profile = 'ADMINISTRADOR'
        elif user.cargo in cashier_roles:
            profile = 'CAIXA'
        elif user.cargo in stock_roles:
            profile = 'ESTOQUE'
        else:
            profile = 'VENDAS'

        if user.perfil != profile:
            CustomUser.objects.filter(pk=user.pk).update(perfil=profile)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cargo',
            field=models.CharField(choices=[('Gerente Geral', 'Gerente Geral'), ('Subgerente', 'Subgerente'), ('Supervisor de Vendas', 'Supervisor(a) de Vendas'), ('Fiscal de Caixa', 'Fiscal de Caixa'), ('Operador de Caixa', 'Operador(a) de Caixa'), ('Vendedor', 'Vendedor(a)'), ('Atendente', 'Atendente'), ('Estoquista', 'Estoquista'), ('Outro', 'Outro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='perfil',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('VENDAS', 'Atendente de Vendas'), ('CAIXA', 'Operador de Caixa'), ('ESTOQUE', 'Operador de Estoque')], default='VENDAS', max_length=20),
        ),
        migrations.RunPython(sync_profiles_from_roles, migrations.RunPython.noop),
    ]
