# Generated by Django 5.0.14 on 2026-06-09 02:19

from django.db import migrations, models


def simplify_market_roles(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    manager_roles = {'Gerente', 'Gerente Geral', 'Subgerente'}
    stock_roles = {'Estoquista', 'Outro'}

    for user in CustomUser.objects.all().iterator():
        if user.is_superuser or user.cargo in manager_roles:
            role = 'Gerente'
            profile = 'ADMINISTRADOR'
        elif user.cargo in stock_roles:
            role = 'Estoquista'
            profile = 'ESTOQUE'
        else:
            role = 'Atendente'
            profile = 'VENDAS'

        CustomUser.objects.filter(pk=user.pk).update(cargo=role, perfil=profile)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_cargo_alter_customuser_perfil'),
    ]

    operations = [
        migrations.RunPython(simplify_market_roles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customuser',
            name='cargo',
            field=models.CharField(choices=[('Gerente', 'Gerente'), ('Atendente', 'Atendente'), ('Estoquista', 'Estoquista')], max_length=100),
        ),
    ]
